#!/bin/sh

set -e

ORJ_LIB_DIR=/var/lib/orj
ORJ_USER="orj"
ORJ_GROUP="orj"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    remove)
        deluser --quiet --system $ORJ_USER || true
        delgroup --quiet --system --only-if-empty $ORJ_GROUP || true
        	# remove workaround for https://bugs.debian.org/1059326
        if [ -L ${GSFONTS_DIR}/n021003l.pfb ] ; then
            rm ${GSFONTS_DIR}/n021003l.pfb
            if [ "$(ls -A ${GSFONTS_DIR})" = ".created-by-orj-package" ] ; then
                rm -fr ${GSFONTS_DIR}
            fi
    	fi
        ;;

    purge)
        if [ -d "$ORJ_LIB_DIR" ]; then
            rm -rf $ORJ_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
